apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: retail-store
  labels:
    app: checkout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
      - name: checkout-service
        image: public.ecr.aws/aws-containers/retail-store-sample-checkout:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: retail-store-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: retail-store-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: retail-store-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: retail-store-secrets
              key: RABBITMQ_PASSWORD
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: retail-store
spec:
  selector:
    app: checkout-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
