apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-store-managed-config
  namespace: retail-store
data:
  # Managed Database configurations (will be updated after RDS deployment)
  MYSQL_HOST: "project-bedrock-mysql.cluster-xyz.eu-west-1.rds.amazonaws.com"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "catalog"
  
  POSTGRES_HOST: "project-bedrock-postgres.cluster-xyz.eu-west-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "orders"
  
  # DynamoDB configurations
  DYNAMODB_REGION: "eu-west-1"
  DYNAMODB_CARTS_TABLE: "project-bedrock-carts"
  DYNAMODB_SESSIONS_TABLE: "project-bedrock-sessions"
  
  # Application settings
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
