apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  namespace: retail-store
  labels:
    app: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
      - name: ui-service
        image: public.ecr.aws/aws-containers/retail-store-sample-ui:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        # Temporarily disable health checks to get services running
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: retail-store
spec:
  selector:
    app: ui-service
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
